name = "Innicia-Server"
author = "_gorbodoh_"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca21712d1021ac929aeb3de4eac1fa18f0904b8857874eda8bd32ecde6e12046"

[versions]
fabric = "0.16.2"
minecraft = "1.20.1"
