name = "Innicia-Server"
author = "_gorbodoh_"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b99db57ae40f0695ee27524638392f7742568c468b0e2c07b09c3c114bc94090"

[versions]
fabric = "0.16.2"
minecraft = "1.20.1"
