name = "Innicia-Server"
author = "_gorbodoh_"
version = "3.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70e88d6089676150d352dbf251edd7aece74c1e2f18a75f9e77d4bf300c6ecc9"

[versions]
fabric = "0.16.2"
minecraft = "1.20.1"
