name = "Innicia-Server"
author = "_gorbodoh_"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f30687f197fefc3f1a3640b0be31c821cc528f7261e2c0c084e437f257271a65"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
