# Walkie-Talkie Config File

# Channel settings
max-canal=16

# Speaker setting
speaker-distance=32
voice-duplication=false

# Walkie-Talkie settings
wooden-walkie-talkie-range=4096
stone-walkie-talkie-range=8192
iron-walkie-talkie-range=16384
golden-walkie-talkie-range=32768
diamond-walkie-talkie-range=65536
netherite-walkie-talkie-range=131072

# Cross dimensions settings
cross-dimensions-enabled=true
apply-dimension-scale=true
